//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Account
{
    public Account()
    {
        this.Articles = new HashSet<Article>();
        this.ArticleCategories = new HashSet<ArticleCategory>();
        this.ArticleMainCategories = new HashSet<ArticleMainCategory>();
        this.ClientCategories = new HashSet<ClientCategory>();
        this.ContactCategories = new HashSet<ContactCategory>();
        this.Products = new HashSet<Product>();
        this.ProductCategories = new HashSet<ProductCategory>();
        this.ProductMainCategories = new HashSet<ProductMainCategory>();
    }

    public string UserName { get; set; }
    public string PassWord { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string FullName { get; set; }
    public string Email { get; set; }
    public string Mobi { get; set; }
    public string Address { get; set; }
    public Nullable<bool> Gender { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string AccountCategoryID { get; set; }

    public virtual AccountCategory AccountCategory { get; set; }
    public virtual ICollection<Article> Articles { get; set; }
    public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }
    public virtual ICollection<ArticleMainCategory> ArticleMainCategories { get; set; }
    public virtual ICollection<ClientCategory> ClientCategories { get; set; }
    public virtual ICollection<ContactCategory> ContactCategories { get; set; }
    public virtual ICollection<Product> Products { get; set; }
    public virtual ICollection<ProductCategory> ProductCategories { get; set; }
    public virtual ICollection<ProductMainCategory> ProductMainCategories { get; set; }
}

public partial class AccountCategory
{
    public AccountCategory()
    {
        this.Accounts = new HashSet<Account>();
    }

    public string AccountCategoryID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }

    public virtual ICollection<Account> Accounts { get; set; }
}

public partial class Article
{
    public int ArticleID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string Keyword { get; set; }
    public string ImageList { get; set; }
    public Nullable<int> ViewTime { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ArticleCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ArticleCategory ArticleCategory { get; set; }
}

public partial class ArticleCategory
{
    public ArticleCategory()
    {
        this.Articles = new HashSet<Article>();
    }

    public int ArticleCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> ViewTime { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ArticleMainCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Article> Articles { get; set; }
    public virtual ArticleMainCategory ArticleMainCategory { get; set; }
}

public partial class ArticleMainCategory
{
    public ArticleMainCategory()
    {
        this.ArticleCategories = new HashSet<ArticleCategory>();
    }

    public int ArticleMainCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> ViewTime { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }
}

public partial class Client
{
    public int ClientID { get; set; }
    public string Code { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public string FullName { get; set; }
    public string Avatar { get; set; }
    public string Thump { get; set; }
    public string Mobi { get; set; }
    public Nullable<bool> Gender { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string ApproveBy { get; set; }
    public Nullable<int> ClientCategoryID { get; set; }

    public virtual ClientCategory ClientCategory { get; set; }
}

public partial class ClientCategory
{
    public ClientCategory()
    {
        this.Clients = new HashSet<Client>();
    }

    public int ClientCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Client> Clients { get; set; }
}

public partial class Contact
{
    public int ContactID { get; set; }
    public string FullName { get; set; }
    public string Email { get; set; }
    public string Adress { get; set; }
    public string Mobi { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string Code { get; set; }
    public Nullable<int> ContactCategoryID { get; set; }

    public virtual ContactCategory ContactCategory { get; set; }
}

public partial class ContactCategory
{
    public ContactCategory()
    {
        this.Contacts = new HashSet<Contact>();
    }

    public int ContactCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Contact> Contacts { get; set; }
}

public partial class OrderDetail
{
    public int ProductID { get; set; }
    public int OrderID { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<double> Price { get; set; }

    public virtual Orderer Orderer { get; set; }
    public virtual Product Product { get; set; }
}

public partial class Orderer
{
    public Orderer()
    {
        this.OrderDetails = new HashSet<OrderDetail>();
    }

    public int OrderID { get; set; }
    public string Code { get; set; }
    public Nullable<double> Total { get; set; }
    public string Email { get; set; }
    public string FullName { get; set; }
    public Nullable<int> PaymentMethod { get; set; }
    public string Comment { get; set; }
    public Nullable<bool> OrderStatus { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public Nullable<bool> DeliverStatus { get; set; }
    public Nullable<bool> ChargeStatus { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
}

public partial class Product
{
    public Product()
    {
        this.OrderDetails = new HashSet<OrderDetail>();
    }

    public int ProductID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public string Keyword { get; set; }
    public string ImageList { get; set; }
    public Nullable<int> ViewTime { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<double> Price { get; set; }
    public Nullable<double> OldPrice { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<int> ProductCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    public virtual ProductCategory ProductCategory { get; set; }
}

public partial class ProductCategory
{
    public ProductCategory()
    {
        this.Products = new HashSet<Product>();
    }

    public int ProductCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }
    public Nullable<int> ProductMainCategoryID { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<Product> Products { get; set; }
    public virtual ProductMainCategory ProductMainCategory { get; set; }
}

public partial class ProductMainCategory
{
    public ProductMainCategory()
    {
        this.ProductCategories = new HashSet<ProductCategory>();
    }

    public int ProductMainCategoryID { get; set; }
    public string Code { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Avatar { get; set; }
    public string Thumb { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<int> Position { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public string CreateBy { get; set; }

    public virtual Account Account { get; set; }
    public virtual ICollection<ProductCategory> ProductCategories { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}
